### ISSUE TITLE
Improve timeout exception handling to prevent flooding Sentry and increase robustness

### ISSUE THREAD

**Issue by alihaberfield** [ACMILabs/playlist-label#14]
This project appears to be the culprit in our Sentry exception event flooding problems, causing us to hit our 5k event quota, after which no Sentry events are accepted. See https://sentry.io/organizations/ACMI/stats/ for verification of this.

The specific exception that appears to be causing the problem is timeoutamqp.transport in _read: https://sentry.io/organizations/ACMI/issues/1213715386/?project=1524888&query=is%3Aunresolved

![image](https://user-images.githubusercontent.com/1869219/67348327-44360f00-f590-11e9-8e71-ef5da8274f76.png)

This ticket is complete when Sentry reporting can be switched on again for this repository without causing us to immediately exceed our event quota.

**Comment by framigni** [comment]
from support:

The only "easy" way to stop a project from sending errors is to simply remove the DSN from the SDK init. An alternative way would be to change the sample rate on the client to the bare minimum (0.01). The latter of course would not stop all events from going through but it would only allow 1% of them. Please refer to your SDK's manual to see how to alter the sample rate.

Lastly, if you have noticed that the errors that generate the most heat are specific, you can use the Inbound Filters to filter them out by error message or IP.

**Comment by framigni** [comment]
this issue is very tricky, considering that:
1. the legacy plan we have subscribed (100k max number of events per month) should well fit our purposes, no needs to change it.
2. we don't want to switch on the "on demand" option, because, if we exceed the 100k threshold, it mans we are logging unnecessary events, so it would be a waste of money
3. experience has shown us that we can get from few thousands events to up to 100k events in just few hours, limiting our reaction time

At this stage, the only practical solution can be:
as soon as we receive the first email warning from Sentry, we do:

1. logon Sentry and check which project is the culprit
2. disable the project DSN
3. investigate which event(s) are the culprit
4. fix the problem on the application or filter out that event(s)
5. re-enable the project DSN
